# ansible-playbook -i hosts sonic-config-playbook.yaml -e "ansible_user=cisco ansible_ssh_pass=cisco123 ansible_sudo_pass=cisco123" -vv

---

- name: sonic-vs tasks
  hosts: sonic-nodes
  become: true
  tasks:

    - name: Copy config_db.json
      copy:
        # src: "../config-unnumbered/{{ inventory_hostname }}/config_db.json"
        src: "../config-numbered/{{ inventory_hostname }}/config_db.json"
        dest: "/etc/sonic/"
        mode: 0644

    - name: Reload sonic to set new config
      command: "sudo config reload -y"
      ignore_errors: yes

    - name: Create a backup of the existing FRR file
      command: mv /etc/sonic/frr/bgpd.conf /etc/sonic/frr/bgpd.conf.bak
      args:
        creates: /etc/sonic/frr/bgpd.conf.bak
      ignore_errors: yes
      register: backup_result

    - name: Copy frr config files
      copy:
        # src: "../config-unnumbered/{{ inventory_hostname }}/frr.conf"
        src: "../config-numbered/{{ inventory_hostname }}/frr.conf"
        dest: "/etc/sonic/frr/bgpd.conf"
        mode: 0644


