
# ansible-playbook -i hosts deploy-playbook.yaml -e "ansible_user=cisco ansible_ssh_pass=cisco123 ansible_sudo_pass=cisco123" -vv

---
      
- name: virsh net tasks
  hosts: localhost
  become: true
  tasks: 

    - name: destroy kvm default / mgt net
      command: "virsh net-destroy default"
      ignore_errors: yes
    
    - name: undefine kvm default / mgt net
      command: "virsh net-undefine default"
      ignore_errors: yes

    - name: define kvm default / mgt net
      command: "virsh net-define ../kvm/mgt-net.xml"
      ignore_errors: yes

    - name: start kvm default / mgt net
      command: "virsh net-start default"
      ignore_errors: yes

- name: Define VMs from XML files
  hosts: localhost
  tasks:

    - name: ls -la
      command: "ls -la ../kvm"
      ignore_errors: yes

    - name: Find XML files in the kvm directory
      find:
        paths: ../kvm
        patterns: "*.xml"
      register: xml_files

    - name: Define VMs using virsh
      command: virsh define ../kvm/{{ item.path | basename }}
      with_items: "{{ xml_files.files }}"
      when: xml_files.matched > 0
      ignore_errors: yes

- name: Start sonic nodes
  hosts: localhost
  vars_files:
    - sonic_nodes.yaml
  tasks:
    - name: Start each sonic node
      command: "virsh start {{ item }}"
      with_items: "{{ sonic_nodes }}"

    - name: pause for 60 seconds to let sonic nodes boot
      pause:
        seconds: 90
      become: false

- name: sonic-vs tasks
  hosts: sonic-nodes
  become: true
  tasks:

    - name: Copy config_db.json
      copy:
        src: "../config-unnumbered/{{ inventory_hostname }}/config_db.json"
        dest: "/etc/sonic/"
        mode: 0644




