virsh_define:
  - ../kvm/sonic01.xml
  - ../kvm/sonic02.xml
  - ../kvm/sonic03.xml
  - ../kvm/sonic04.xml
  - ../kvm/sonic05.xml
  - ../kvm/sonic06.xml
  - ../kvm/sonic07.xml
  - ../kvm/sonic08.xml
  # - ../kvm/sonic09.xml
  # - ../kvm/sonic10.xml
  # - ../kvm/sonic11.xml
  # - ../kvm/sonic12.xml